import Head from 'next/head'
import { useState } from 'react';

export default function Home() {

  const [file, setFile] = useState(null);

  const handleUpload = async (e) => {
    e.preventDefault();

    if (file) {
      console.log("file: ", file);
      console.log("Uploading file...");

      const formData = new FormData();
      formData.append('file', file);

      try {
        // You can write the URL of your server or any other endpoint used for file upload
        const result = await fetch("http://localhost:3000/api/uploadfile", {
          method: "POST",
          body: formData,
        });

        const data = await result.json();

        console.log(data);
      } catch (error) {
        console.error(error);
      }
    }
  }

  const handleSetImage = (event) => {
    if (event.target.files) {
      setFile(event.target.files[0]);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" }}>
        <form encType="multipart/form-data">
          <br />
          <input type="file" onChange={e => handleSetImage(e)} />

          <button type="submit" onClick={handleUpload}>Submit</button>
        </form>
      </div>
    </>
  )
}
